name: Biome Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Check
        run: |
          # Simulating an error
          echo "::error file=src/index.js,line=10,col=5::Syntax error found in this file"
          
          # Simulating a warning
          echo "::warning file=src/index.js,line=15,col=3::Variable is not used"
          
          # Simulating a notice
          echo "::notice file=src/index.js,line=20,col=2::Consider refactoring this code"